### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jerozeek** [agungsugiarto/codeigniter4-authentication-jwt#1]
[InvalidArgumentException]                                                                                                                                      
  Could not find a version of package agungsugiarto/codeigniter4-authentication-jwt matching your minimum-stability (stable). Require it with an explicit versio  
  n constraint allowing its desired stability. 
I got this message when i tried to install the package on codeigniter 4.1.2

**Comment by agungsugiarto** [comment]
First edit your `composer.json` to minimum stability dev

- https://getcomposer.org/doc/04-schema.md#minimum-stability
- reference https://github.com/agungsugiarto/codeigniter4-authentication-demo/blob/79a0d1a758d02195a5e1c8341b56d1bf1912a1ef/composer.json#L36-L37

**Comment by jerozeek** [comment]
Thanks for the quick response. Its now working
