### ISSUE TITLE
codeigniter4-authentication-jwt - Dont Work With PHP 8.*

### ISSUE THREAD

**Issue by luciomdesouza** [agungsugiarto/codeigniter4-authentication-jwt#4]
Hello!

Hello Agung Sugiarto!

With PHP 8.0, I am facing the following error:

Call to undefined method Lcobucci\\JWT\\Builder::withClaim()

File: \\vendor\\agungsugiarto\\codeigniter4-authentication-jwt\\src\\Providers\\JWT\\Lcobucci.php

With version 8.1, another error happens:

<b>Fatal error</b>: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Fluent\JWTAuth\Claims\Claim::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the # [\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\employees\vendor\agungsugiarto\codeigniter4-authentication-jwt\src\Claims\Claim.php:146

I already put the attribute #[\ReturnTypeWillChange] in each method, but at the end of that the message appears:

Call to undefined method Lcobucci\\JWT\\Builder::withClaim()

File: \\vendor\\agungsugiarto\\codeigniter4-authentication-jwt\\src\\Providers\\JWT\\Lcobucci.php

This error does not happen with PHP 7.4. I appreciate if you can guide me on how to solve it.

**Comment by agungsugiarto** [comment]
Hello @luciomdesouza thank you for your feedback, this issue is already fixed with this pr #5, check this out.
