### ISSUE TITLE
Call to undefined method Lcobucci\\JWT\\Builder::withClaim()

### ISSUE THREAD

**Issue by luciocodeigniter** [agungsugiarto/codeigniter4-authentication-jwt#6]
Hello Agung Sugiarto! Even after you fixed the codeigniter4-authentication-jwt - Dont Work With PHP 8.* #4 issue, I'm still facing the following error:

{
     "title": "Error",
     "type": "Error",
     "code": 500,
     "message": "Call to undefined method Lcobucci\\JWT\\Builder::withClaim()",
     "file": "C:\\laragon\\www\\employees\\vendor\\agungsugiarto\\codeigniter4-authentication-jwt\\src\\Providers\\JWT\\Lcobucci.php",
     "line": 106,

//...

I appreciate if you can guide me on how to solve it.

**Comment by agungsugiarto** [comment]
I think it's because different version from lcobucci/jwt, "lcobucci/jwt"​: ​"​<3.4​"​ ?

**Comment by luciocodeigniter** [comment]
I do not understand...

In your package the codeigniter4-authentication-jwt/src/Providers/JWT/Lcobucci.php class

has the withClaim() method,

If this is true, how does this error occur?

**Comment by agungsugiarto** [comment]
You can read this #3

**Comment by agungsugiarto** [comment]
Hello @luciocodeigniter i have same issue when using php 8.x, since lcobucci/jwt <3.4 does not support with php 8.x. I will look into it to upgrade lcobucci/jwt to last version or just fix this issue.

**Comment by agungsugiarto** [comment]
Already fixed https://github.com/agungsugiarto/codeigniter4-authentication-jwt/pull/7

**Comment by luciocodeigniter** [comment]
Thanks for the quick solution!
