### ISSUE TITLE
Error installing via Composer 

### ISSUE THREAD

**Issue by seunex17** [agungsugiarto/codeigniter4-authentication-jwt#8]
Hello I am using your version 2 Auth package I will like to use this JWT package as rest API with you AUTH package I install. 

When try to install this package via COMPOSER it throw error that my MINIMUM requirements is STABLE .

Please can you create a RELEASE version

**Comment by agungsugiarto** [comment]
Hello @seunex17 thank u for submitting issue, already fixed with pr https://github.com/agungsugiarto/codeigniter4-authentication-jwt/pull/9
